#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AgilePlanningPoker.Droid.Resource", IsApplication=true)]

namespace AgilePlanningPoker.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blankcard = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int card_0 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int card_1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int card_100 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int card_13 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int card_2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int card_20 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int card_3 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int card_40 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int card_5 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int card_8 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int card_coffee = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int card_questionmark = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int gridView1 = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int imageView1 = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Layout2 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
